### ISSUE TITLE
Right-click and left-click hitboxes do not match.

### ISSUE THREAD

**Issue by codewarrior0** [jaquadro/StorageDrawers#167]
Using version 1.6.2 (as part of FTB Infinity Evolved 2.1.2).

It is simplest to show this visually:

![image](https://cloud.githubusercontent.com/assets/307683/11356875/fcac78a0-9205-11e5-970b-b667784e6b7d.png)

The **blue** lines indicate the borders between the hitboxes when *left-clicking*.
The **green** lines indicate the borders when *right-clicking*.

In other words, the right-click hitbox correctly matches the pixels, while the left-click hitbox does not.

The situation is similar for compacting drawers.

**Comment by codewarrior0** [comment]
Update: This behavior seems to vary depending on which way the drawer is facing. The above drawer was facing X+ or Z+.

With a drawer facing X- or Z-, these edges are observed:

![image](https://cloud.githubusercontent.com/assets/307683/11357027/9e7a909e-9207-11e5-9533-84067c22e885.png)

**Comment by jaquadro** [comment]
Interesting catch.  It looks like a roundoff error in the BlockClickMessage.  Minecraft gives me the the right-click hit vector on the server, but forces me to calculate my own left-click hit vector on the client and send it through a custom packet.

**Comment by codewarrior0** [comment]
Nice. I was wondering how that worked, since vanilla Minecraft blocks don't do anything besides break when you left-click on them.

**Comment by jaquadro** [comment]
Fix available in 1.7.0.

**Comment by codewarrior0** [comment]
BTW, this issue is present in v2.2.1 for MC 1.8.9 where the hitboxes are slightly different, but still wrong.

**Comment by jaquadro** [comment]
Ah yes.  The 1.8 branch mostly stalled out after a bad merge in August.  Save for some 1.8-specific improvements recently.  Need to pick that up again.
