### ISSUE TITLE
[1.10.2] Storage Drawers are gone after restart

### ISSUE THREAD

**Issue by KendziGE** [jaquadro/StorageDrawers#323]
Hey, 

I play the FTB Unstable 1.10 pack (Version 4.2.5), and I know, its called Unstable. But I think, better report it ^^
I placed Storage Drawer's, after a restart, the drawer's are gone, only a light shadow is on the ground, where the drawer's stand. 
And there's a situation, that only a few Drawers are gone. 
In my playworld 12 Drawer's (different, Basics, 2x1 2x2) are there, I can use them, one chunk further, my compact drawers are gone. Placed a few seconds after the 12 normal drawer's. 

In my Creative-Testworld, I tested this, placed drawer's, saved - restart, drawers are gone. Try'd with different Chunks, all drawers are gone, after a restart.

Sorry for my bad english ^^, I hope my report is helpful.

**Comment by lilrichy** [comment]
Same thing is happening on my server Drawers are not rendering.

This is possibly a bug due to forge updating and fixing a vanilla bug in 12.18.1.2027. 

Botania has a similar issue after I updated my server.

**Comment by jaquadro** [comment]
- Single player or multiplayer?
- Is there anything reported in your logs?
- If you upgrade to Forge 2042 is it still happening?

I updated my environment to 2042 and I'm not seeing this in my environment.  Worst I saw loading my test world is framing tables seemed corrupted and needed to be replaced.

**Comment by KendziGE** [comment]
Singleplayer, but I have seen a "report" on the cursepage, that was on a server. 

I can't upgrade to 2042 because, crash on startup. Sorry :(

The only thing in the logs was http://pastebin.com/K2FLu96x
I took the pictures in a new creative world, My fail, I was thinking this is with the 2042, but it was the 2027 forge version.
Here a Picture before I saved http://i.imgur.com/7q1AK3p.png
And here after I startet the world again http://imgur.com/RtWm5yu

Not on the pictures, the "shadows" where the drawers stand. If you go to the place, the shadows became a little bit weird, the arm/hand became a shadow.

offtopic: can be ignored: btw, this is my crash report on startup with the 2042 http://pastebin.com/tDaeN0aP , but I have no idea why/ what I can change to make it run.

**Comment by DefiantZombie** [comment]
MC: 1.10.2
Forge: 12.18.1.2027 (original was incorrect with 2043)
Chameleon: 1.9.4-2.1.6
Drawers: 1.9.4-3.2.1

Drawers are disappearing at seemingly random. Can't pin down an exact cause. One minute you're working with the drawers, the next you turn around and there's just a shadow left behind where the blocks were.

Haven't seen this in single player (yet), but it has happened several times on my fresh server install. Nothing pops in the running server log when it happens.

Edit: Reported incorrect Forge version.

**Comment by DefiantZombie** [comment]
UPDATE:

Attempted dropping a new drawer next to the shadow. The shadow disappeared. When placing a drawer where the "dead" drawers were an item that was stored there popped out. I was able to drop new drawers where the old ones disappeared from and punch all my items back to inventory. When I placed the new ones down they had no item icons on them (as expected).

UPDATE 2 (forgot you can edit comments):
Player can collide with bad drawers, but tools cannot. Placing a new drawer on the dead one, emptying, then breaking results in 2 drawers given. Player's empty hand counts as a tool.

**Comment by lilrichy** [comment]
@jaquadro 
- This is happening on the multiplayer server I run. 
- Logs say nothing.
- Still happens after upgrading to Forge 12.18.1.2043

**Comment by polyflakes** [comment]
i am having the same issue i will place a drawer down fill it then log off and back on and its not rendered. if i place a block in the same location and break it i get the drawer and items back  as if i broke the drawer. 
also on server reset the drawer seems to be removed altogether.  
also when connected to a drawer controller the controller stays put on drawer still dose not render on relog .
its  odd because i have been testing and in both cases i was having this happen  i moved the drawer setup to a different position in the chunk had the issue stopped happening? 

MC1.10.2 
 forge  currently 2033 and 2043 (minimal testing done in 2043 as i had to remove a mod to test due to crash on server start)  
multiplayer 
StorageDrawers-1.9.4-3.2.1

**Comment by der10pm** [comment]
I'm wondering whether it's possible to be a sort of desync issue.
Currently running forge 2027 on client and 2039 on server an and as i place the drawer(basic one as well as 2x2) they seem to vanish on chunk reload, but i think they just aren't rendered on client side anymore as they still have got this wacky collision box and enderio conduits seem connected/items are transferred. But as i restarted the server the drawers completely vanished - no collision/connected conduits whatsoever.

Little addition:

Had a friend help me out on it. Placed drawer in front of them and they told me, they couldn't see it. Collision was still there

**Comment by jaquadro** [comment]
Probably some kind of block/tile sync problem, yeah.  If one or the other is missing it's not going to render.  But if one or the other is missing, it will still retain some behaviors.

**Comment by der10pm** [comment]
I sadly don't have the option for additional testing and my biggest question was if it's issued by the mod itself or some strange incompatibility with another mod in the pack. 
Or is anyone having the issue outside of FTB Unstable?

**Comment by jaquadro** [comment]
Recent Forge updates have thrown a lot of mods into the lurch (so what I hear, anyway).  I'm trying to get some information from other authors who have been seeing problems.

**Comment by der10pm** [comment]
One thing that works(at least in my case) was reverting to forge 2011. 
Can't say for sure which version broke things atm.

**Comment by jaquadro** [comment]
Can anyone test if there's an improvement on Forge 2044?

**Comment by kwpugh** [comment]
Not sure if this is related, but had same issue with disappearing drawers.   The drawers were in a chuck claimed by a team with FTBUtilities.   I removed all claims by command and everything was fine.   Running forge 2043.

**Comment by bagofsquirrels** [comment]
I just checked with Forge 2044 and that appears to have fixed it. Drawers are no longer disappearing.

**Comment by DefiantZombie** [comment]
Okay after lots of restarts and relogging, here's what I've determined: The problem isn't with Forge.

It's a FTB Utilities/FTB Lib problem. The bug occurred with any Forge version I tried 2027-2044. As soon as FTB Utilities and associated library are removed, the bug goes away. This fits with a bunch of other random bugs I associate with FTB Utilities and chunk claiming/loading. It's affecting far more than just the Drawers mod.

If everyone seeing this bug could report their FTB Utilities/FTB Lib versions (if installed), that should help the Drawers team out.

**Comment by kwpugh** [comment]
I'm using:

FTBLib-1.9.4-2.1.0-pre2.jar
FTBUtilities-1.9.4-2.1.0-pre2.jar
StorageDrawers-1.9.4-3.2.1.jar
Chameleon-1.9.4-2.1.6.jar

**Comment by lilrichy** [comment]
@DefiantZombie I am using the same versions of all mods as @kwpugh If that is the case I will probably just remove the ftb utilities, till this is fixed.

**Comment by MerlinQ** [comment]
I also have the same mod versions as @kwpugh.

Forge 2044 fixed it though.
If you read the forge patch notes, 2044 is the second try at fixing an error that made some blocks disappear by incorrectly saving certain types of block data.
FTBUtilities probably would add these types of block data to some blocks, thus triggering the error on blocks that would not usually be affected.

**Comment by kwpugh** [comment]
I updated to Forge 2044, did not fix it.   I removed FTBUtilities and FTBLib and problem went away.   Also cleared up a problem with another mod as well that was stumping the author.

**Comment by MerlinQ** [comment]
Odd, it worked for me, we don't use FTBUtilities' chunk protection features though, that might be affecting it.

Sorry it didn't work for you, hope it gets sorted.

**Comment by kwpugh** [comment]
No problem, I was planning on dumping FTBU anyway for other reasons.

**Comment by jaquadro** [comment]
Paging @LatvianModder - Is this something you could help investigate?

**Comment by ariosos** [comment]
Can confirm in version 2011 for single player. Updating to 2044 crashes the game, so I'll have to dig around and see what mod caused it (don't have time right today to do that).

Mod list (from the crash log) - http://pastebin.com/HpHh3Nan

**Comment by der10pm** [comment]
Vazkii just tweeted that Charset crashes on the newest forge

**Comment by Okimo** [comment]
So If I have Save when i had FTBU on then my save is corrupted and I can't stop drawers dispearing?

**Comment by Darthvrael** [comment]
I only had this issue when connecting Drawer controllers to drawers. Both the controller and the drawers connected would disappear when reloaded. 

I have not had the issue since updating to forge 2045 (originally version used was 2027).

**Comment by Giovanni-NL** [comment]
Looks like the problem is not only with Storage Drawers. The modpack I play has StorageDrawers-1.9.4-3.2.1 in combination with FTBUtilities-1.9.4-2.1.0-pre2 and I am also experiencing drawers disappearing seemingly random in chunks claimed with FTBUtilities.  But today, I am also missing a furnace from the MoreFurnaces-1.10-1.8.1 mod.  Same effects happening, the furnace seems to be there, but it's not visible anymore.  Can't walk into the spot where is stood/stands though.  

Also, the content of the storage drawers that went missing seem to be still accessible via an EnderIO inventory panel connected to the storage controller.  However, the one drawer that should be holding 32 stacks of sticks max. now holds 85k (autocrafted) sticks, and all the wood and planks in the system are gone.  So it seems the invisible drawer somehow lost some data which prevents you from putting in more than it's intended maximum.

Forge version 2027 by the way.

**Comment by LatvianModder** [comment]
I will see if there's anything I can do. I know for sure that I used SD a lot in my claimed chunks and had no problems (on dedi server, not only test world)

**Comment by LatvianModder** [comment]
The only thing FTBU only does with world/blocks is _sometimes_ prevents blocks from being placed / broken. So either its a visual glitch or I dunno

**Comment by Giovanni-NL** [comment]
Thanks for looking into this. We can try upgrading Forge to the latest version (2046) next monday, and see if that changes anything.  Still, kinda odd that the problems go away when the FTB Utilities are not used.

Also, seems to be more than just a visual glitch.  Storage drawers first disappear visually, but leave behind ghost blocks.  But after a server reset, the storage drawers are actually gone.  Lighting is restored to normal in those places, and you can walk on the spots where the storage drawers used to be,

**Comment by Giovanni-NL** [comment]
Upgraded to Forge 2046 yesterday.  So far none of the storage drawers I placed after that have disappeared.  Fingers crossed...

**Comment by jaquadro** [comment]
Going to assume this was put to rest with the recent Forge updates.

**Comment by Giovanni-NL** [comment]
Yup. 16 days later now. Drawers still ok :)
