### ISSUE TITLE
Storage drawers don't update their redstone output when they receive items through a drawer controller. 

### ISSUE THREAD

**Issue by ghost** [jaquadro/StorageDrawers#340]
I found that if you insert (or take out) items through the drawer controller then the redstone output of drawers with Redstone upgrades don't update.

http://imgur.com/a/u8IL8

Pictures detailing the issue.

Interacting the drawer itself works as expected. I guess when items are inserted through a drawer any connected drawers with redstone upgrades need to check their ouput. As it is makes stock level automation impossible.

**Comment by ghost** [comment]
Did some more testing. Even though I was only using ender IO redstone conduits the same issue applies to vanilla redstone too. 

When I put the drawer into the un-updated redstone output state and provided a block update to the drawer nothing happened. Updated the redstone dust and it corrected the ouput

**Comment by xannor** [comment]
Hah, I was just in the process of submitting this one myself, though I didn't make the controller connection. In fact I just tested this and as soon as I pulled an item the redstone updated.

**Comment by xannor** [comment]
The before pulling a single item:
http://imgur.com/a/YiHBd
http://imgur.com/cShe4qt
The after:
http://imgur.com/a/kfaLZ

for me this is in 1.10.2

**Comment by ghost** [comment]
@xannor Looks like we're doing exactly the same thing XD Mine goes into a comparator with a dirt chest too!

Forgot to say. This is with the latest 1.10.2 versions of storage drawers and chameleon.

**Comment by jaquadro** [comment]
Fixed in 1.7.10-1.10.2 (no, that has nothing to do with the MC 1.10 version).

The 1.10 version will follow soonish.

**Comment by xannor** [comment]
Which version for 1.10.2 contains the fix? I am running 3.2.7 and the redstone is still not updating when the drawer changes, I have to manually add/remove for it to update.

**Comment by ghost** [comment]
Umm.. Where is the 1.10.2 version then? :question:

**Comment by jaquadro** [comment]
So I know I'm pretty late on this.  I lost time for modding for a while.

This is now fixed in 3.4.0.
