### ISSUE TITLE
[1.12] Incorrect Rendering of Redstone Upgrades

### ISSUE THREAD

**Issue by SnowShock35** [jaquadro/StorageDrawers#505]
Hi @jaquadro,

Another, what I believe to be, issue for you. Here's the details;

### Issue Information

- Minecraft 1.12
- Minecraft Forge 14.21.0.2234 (Latest at current time)
- Chameleon 1.12-4.0.0
- Storage Drawers 1.12-5.0.4

### Issues Details

The Redstone, Redstone Min and Redstone Max Upgrade all have incorrect rendering when held in the players hand as well as when they're in-world entities. Perhaps a missing or incorrectly configured JSON file.

### Issue Media 

![](https://ss.blamesnow.co.uk/2017/06/1497776284-5d0390f2.png)

**Comment by jaquadro** [comment]
Fixed in 5.0.5

**Comment by SnowShock35** [comment]
@jaquadro Still not fixed in 5.0.6. Unsure as to why 😕

**Comment by SnowShock35** [comment]
@jaquadro This issue is still not fixed. Unsure as to why. Would you be able to look into it further?

**Comment by jaquadro** [comment]
This should be fixed fixed in 5.2.1.
