### ISSUE TITLE
[1.11.2] Lost Upgrades going from 1.10.2

### ISSUE THREAD

**Issue by JohnRohner** [jaquadro/StorageDrawers#523]
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgraderedstone, id 4116
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:personalkey, id 4121
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgradestatus, id 4119
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:drawerkey, id 4117
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgradevoid, id 4126
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgradecreative, id 4112
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgradetemplate, id 4122
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:upgradestorage, id 4115
[16:08:52] [Server thread/FATAL] [FML/]: Unidentified item: storagedrawers:shroudkey, id 4113

This occurs when going from a 1.10.2 server world to 1.11.2 and 1.12 using the latest version of Storage Drawers.  Mainly I'm interested in the full indicators.

Any quick fix, or is this just an artifact of upgrading and I have to manually re-add them?

Thanks

**Comment by JohnRohner** [comment]
Also: In 1.11.2 the first time a shift-right-click is done on a basic wood 4-drawer box it wipes out many of the slots and  clears that drawer (but not the whole box).  Some also have there count wrong.  These are basic 512 item drawers.  Don't remember if I upgraded them to get 512 but that might explain it.

Compacting drawers do not have the right click problem.

To get around this I just clean out the box drawers with shift-left clicks.

However, when putting items back into the drawer, and shift-right-clicking will give the count, then magically give me a stack of that item--without it reducing it from the drawer (and seemingly put one of the items into the air or on front of the box as well).

**Comment by jaquadro** [comment]
There were some ID changes going from 1.10 to 1.11.  1.11 to 1.12 should be smooth (barring the major 1.12 update I'm working on now, which will make a best effort to migrate the data).

For your second comment -- sync issue?  If you close the world and open it again, are the contents what they should have been?

**Comment by JohnRohner** [comment]
The contents do reappear whenever the client is reloaded.

I found that going into creative and grabbing some redstone upgrades and indicator upgrades, and then going into survival and applying them do seem to fix the shift-right-click issues.  That is, the contents don't disappear and it's not acting all weird.

Still, I need to review what I did to make the full indicator's, as it seemed like the redstone upgrade plus indicator upgrade worked best, as when I just did the indicator upgrade it seemed to still be dropping half the drawers.  Will try it for real later and report back.

In code, it's got to be that even though the indicators were stripped out something is remaining that is telling the code something is there, but then can't find it and so goes all screwy.

shift-right-click on a 4x4, then for a second I see the contents in the popup, then they're wiped away from the popup display and the minecraft display.

Thanks

**Comment by jaquadro** [comment]
The indicators and redstone upgrades both result in extra (but not identical) syncing between server and client.  That could be masking it.

I swear I fixed the sync issues recently, so that's frustrating.  Did you try to get them on 1.12?  I'm about to release an alpha build that really shakes things up there.

**Comment by JohnRohner** [comment]
Adding the missing fullness indicators did not solve the problem.  shift-right-click still showed the same behavior.  I think the other weirdness I was noticing was because I was right-clicking to add blocks into a drawer that SD thought/showed was empty--and so disappeared the items from my bar--but really wasn't and so they were still hidden items in the bar.  Noticed that when I pulled items out drawers it refused to populate seemingly blank bar boxes.

Same results with both setups:  11.2: forge 2393, sd 4.2.10, cam 3.1.0,  12.0: forge 2387, sd 5.1.3, cam 4.0.2 with 2x2 x8 basic drawers.  I can email you the world if you'd like--it's down to just the two mods.

**Comment by JohnRohner** [comment]
Just tried 12 with cham 4.1.0 and same result.  Seems like it may be related to contents size.  Like over 128 items it's zapping.
