### ISSUE TITLE
Protection Issue

### ISSUE THREAD

**Issue by SirWilli** [jaquadro/StorageDrawers#62]
hey,
it would be great if the items don't get delivered to the player if the interaction event get canceled from a other mod. As it is impossible to protect the storage drawers currently.

**Comment by jaquadro** [comment]
Never crossed my mind.  Can you recommend a test case?

**Comment by SirWilli** [comment]
Sorry, I'm not sure what do you mean with test case, can you elaborate?

**Comment by jaquadro** [comment]
I'm not familiar with anything canceling interaction events.  How would you suggest I reproduce this for testing a fix?

**Comment by SirWilli** [comment]
I just wrote a simple mod which cancels the event like this:
```

**Comment by jaquadro** [comment]
I've run into a problem with this.

JABBA works correctly on left-click because it's handling the server-side onBlockClicked event, and that gets suppressed by the PlayerInteractEvent.

In my case, I need to have sub-block-resolution click data, which is not included with the standard onBlockClicked event.  That means I have to handle the event client-side and dispatch a packet with the extra data, and then handle that server-side.  Unfortunately, the PlayerInteractEvent does NOT attempt to intercept the client-side block-left-click event.

If you have other ideas to pursue I'll take a look, but otherwise the best I can think of is providing my own cancelable event that another mod could intercept.

**Comment by Xfel** [comment]
You could simply fire the PlayerInteractEvent yourself in your server-side packet handler. 
```
PlayerInteractEvent event = ForgeEventFactory.onPlayerInteract(player, action, x, y, z, face, world);
if (event.isCancelled()) {
    // don't process
    return;
}
// proceed...
```
This has the advantage that it works with generic protection handlers.

**Comment by jaquadro** [comment]
That crossed my mind, but I was somewhat concerned about firing an event in an unexpected place.

**Comment by Xfel** [comment]
Why would that be an unexpected place? The call stack doesn't really matter so it should work after all.

**Comment by SirWilli** [comment]
Any news to this?

**Comment by jaquadro** [comment]
This should be fixed in [1.4.0-alpha2](http://minecraft.curseforge.com/mc-mods/223852-storage-drawers/files/2235914).

**Comment by Slind14** [comment]
It seems like that this broke upwards of 1.6.2 somewhere, can this be?

**Comment by knoxz** [comment]
Removing an item prompts the Protection message but you still get the item.
When you try to add something, there is a client server desync. The item appears to be in the drawer, on a other update (Reloging / clicking the drawer / inventory sort), the item reappears in your inventory and disappears on the drawer.
