### ISSUE TITLE
Void upgrade not working with AE2

### ISSUE THREAD

**Issue by Amadeus99** [jaquadro/StorageDrawers#72]
I am using 1.4.0 and AE2 rv2-beta-29. (Agrarian Skies 2 modpack but I updated some of the mods)  I have an Applied Energistics 2 Storage Bus connected to a Drawer Controller.  The Storage Bus has the highest priority of all buses and drives.  I also have void upgrades on all drawers.  I am importing items into the system via an Import Bus.  Items will go into drawers first correctly.  However, if a drawer gets full, items are put into the AE2 Drive even when there are void upgrades on the drawers.  As in it seems that AE2 sees the drawer as full, ignores/doesn't know about the void upgrade, and therefore won't send items to the Drawer Controller.  Could you change this behavior so that the Drawer Controller can still get items from AE2 for items in full drawers that have void upgrades?  My wild guess is that you have to lie to AE2 about the size of a drawer with a void upgrade.  Or is this something I have to see if the AE2 team can do?  Let me know if you need any other information.  Thanks.

**Comment by jaquadro** [comment]
AE2 works through the same interface as manually adding items, which ignores the void upgrade.  So you are right, I will need to make a change specific to AE2.

**Comment by jaquadro** [comment]
Should be resolved in 1.4.1 now.

**Comment by Amadeus99** [comment]
Wow, that was fast. =)  Thanks.

**Comment by Amadeus99** [comment]
I updated to 1.4.1 and it is still not working.  Overflow is ignoring the drawer with the void upgrade and going in to the me drive.  Let me know if you need any other info or want me to test something.

**Comment by jaquadro** [comment]
Hm, okay, I think this is a partial fix.  I forgot you mentioned controller specifically.  I tested with a storage bus directly on a drawer, and that should work in 1.4.1 now.

The controller will be trickier to solve.

**Comment by Amadeus99** [comment]
Working great!  Thanks.
